common: &common
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  pool: 5

development:
  <<: *common
  database: vintage_development

test:
  <<: *common
  database: vintage_test