common: &common
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  pool: 5

development:
  <<: *common
  database: party_shark_development

test:
  <<: *common
  database: party_shark_test